spring:
  # Spring JMX
  jmx:
     enabled: false
  # H2 Embedded DB settings
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
  # Datasource settings
  datasource:
    url: jdbc:h2:mem:recommendDB;INIT=CREATE SCHEMA IF NOT EXISTS recommend\;CREATE SCHEMA IF NOT EXISTS lookup\;SET SCHEMA recommend;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
        connection-timeout: 60000
        maximum-pool-size: 5
  # Jpa settings
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop # Hibernate ddl auto (create, create-drop, validateData, update)
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
# Logging specifics
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: TRACE
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Spring Security : make sure to always enable security in production
#security:
#  basic:
#    enabled: false
#    ignored: /**



##Spring management endpoints on a separate port
#management:
#  port: 8091
#  security:
#    enabled: false # management port is internal only. We disable it for now.

